src/pages/_app.tsx
**やったこと**
- src/pages/_app.tsxに、テーマを設定
- テーマにてRobotoフォントを設定
**参考にした記事**
[https://chakra-ui.com/docs/styled-system/customize-theme](url)
[https://qiita.com/manak1/items/de1a15446c6154bed699](url)
close #13
=> #13 add: フォント設定

src/pages/todonew.tsx
=> #9 todo new　TodoNewページデザイン変更/共通ヘッダに変更

src/components/FormArea.tsx, src/components/Layout.tsx, src/pages/login.tsx, src/pages/signup.tsx
componentsディレクトリを作成し、その中にFormArea.tsxを作成
pages配下にlogin.tsxを作成
pages配下にsignup.tsxを作成
close #5 #12
=> ログイン、サインインデザイン作成

src/pages/todonew.tsx
=> #9 todo new　コンテンツを中央1080px固定

src/pages/TodoTop.tsx
**やったこと**
1. Todo Top ページの作成
2. Emotion を使用してデザイン調整
svgに関しては、一旦、ライブラリ等を用いずにインラインで書いてます。
close #2
=> #2 todo top 作成

src/pages/todoedit.tsx
=> #4 add : 修正

src/pages/todo_show.tsx
=> #6 add: todo-show作成

package.json, src/atom.js, yarn.lock
**やったこと**
1. jotai をインストール
2. atom定義ファイル作成
atom定義ファイルがあったほうが良いらしいので、作成しました。
参考記事
https://qiita.com/daishi/items/0a821f712cbb3f9edb2d
https://zenn.dev/kkeeth/articles/studying-jotai-library
close #26
=> #26 import jotai

src/utils.tsx
**やったこと**
- utils.tsx ファイルを作成
- formatDateStr関数 を定義
close #33
=> #33 formatDateStr関数を定義

src/pages/todonew.tsx
=> #24 add:新規登録実装

next.config.js, src/pages/TodoTop.tsx
一旦TodoTopの以下機能について実装しました。
レビューをお願いいたします。
■対応したこと
・一覧表示（Firebaseデータ取得、表示）
・タイトルの詳細リンク追加　※リンク仕様確認済み
・編集リンク追加　※リンク仕様確認済み
・削除機能追加
次の対応予定です。順次適用してきます。
■残対応
・一覧表示フィルタ
・優先順位変更（即時変更）　
・ページネーション
=> #2 refactor: TodoTop一覧表示/編集リンク/削除機能追加

src/pages/[id]/todo_show.tsx
**やったこと**
- Backボタン押下で、TodoTopへ遷移
- Editボタン押下で、TodoEditへ遷移
- hrefでのid使用のため、id取得方法変更
close #35
=> #35 todo show back edit

src/pages/todonew.tsx
=> #39 add:indexページへの遷移

src/pages/404.tsx, src/pages/[id]/todo_show.tsx, src/pages/[id]/todoedit.tsx
**やったこと**
- 以下のページでTodoTopへの遷移をindexに遷移するように変更
- todoedit.tsx
- todo_show.tsx
- 404.tsx
close #45
=> #45 refactor: TodoTopのパスをindexに変更

src/pages/todonew.tsx
遷移できていると思います！
一つ気になったのがindexページに移動した後に出たエラーです。
このエラーは他のページから移動した際にも出てるのでしょうか？
=> #50 add:"/"修正

src/pages/[id]/todoedit.tsx
=> #49 add: todoeditの文字数制限

src/components/TodoList.tsx, src/pages/index.tsx
旧TodoTop（index）にstatusクリック時変更する処理を加えましたので、レビュー願います。
=> #2 refactor: 旧TodoTop(index)一覧　statusクリック時変更処理追加

src/pages/todonew.tsx
React Hook Formは使わずにバリデーションを実装しましたので、React Hook Formのインストール自体をキャンセルしています！！
yarnコマンドは押していただかなくて大丈夫です、ややこしいこと言ってしまいすみません！
=> add:バリデーションの実装

src/pages/todonew.tsx
複数のタスクを一つのissueにまとめました、
変更箇所が多いですがレビューよろしくお願いいたします！！
=> #60 add:Todonewの文字数修正、create後topにリダイレクト、draftボタン削除

src/pages/[id]/todoedit.tsx
=> #57 fix: Todoeditの文字数制限の変更

src/pages/[id]/todo_show.tsx, src/pages/[id]/todoedit.tsx
**やったこと**
- 存在するtodoidかチェック
- 存在しないtodoidの場合、404ページへ遷移
close #56
=> #56 動的ルートのtodoidを検証

src/pages/[id]/todo_show.tsx
**やったこと**
- DETAILの高さを可変に
- コメント欄のスクロールを削除
close #55
=> #55 todoshow DETAILの高さを可変に変更

src/pages/[id]/todoedit.tsx
TodoEditのsubmitクリック時エラー回避処理追加しました。
then()でDB更新完了を受けてから/へリダイレクトするようにしています。
.then(() => {
router.push({
pathname: "/",
});
})
.catch((error) => {}
=> #4 refactor: TodoEdit　submitクリック時エラー回避処理追加

package.json, src/pages/[id]/todo_show.tsx, src/utils.tsx, yarn.lock
**やったこと**
- ReactHookForm の導入
- バリデーションの追加
- コメント欄の調整
- formatDateStr関数に時刻なしの分岐を追加
close #66
=> #66 コメント作成時、バリデーションを追加
